steps:
- name: 'bash'
  args: ['echo', '##########  First Step ############']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/car-eu-playground-sco-nprd/test-deploy:tag4', 'test-deploy/.' ]
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/car-eu-playground-sco-nprd/test-deploy:tag4']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
  - 'run'
  - 'deploy'
  - 'test-deploy-tag2'
  - '--allow-unauthenticated'
  - '--image'
  - 'eu.gcr.io/car-eu-playground-sco-nprd/test-deploy:tag3'
  - '--region'
  - 'europe-west3'
  - '--platform'
  - 'managed'
images:
- eu.gcr.io/car-eu-playground-sco-nprd/test-deploy:tag3
