steps:
- name: 'eu.gcr.io/car-eu-playground-sco-nprd/test-deploy'
  args: [ 'build', '-t', 'eu.gcr.io/car-eu-playground-sco-nprd/test-deploy/quickstart-image:tag1', '.' ]
images:
- 'eu.gcr.io/car-eu-playground-sco-nprd/test-deploy/quickstart-image:tag1'
