steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west3-docker.pkg.dev/car-eu-playground-sco-nprd/eu-carops-repo/quickstart-image:tag1', '.' ]
images:
- 'europe-west3-docker.pkg.dev/car-eu-playground-sco-nprd/eu-carops-repo/quickstart-image:tag1'
